#服务端口配置
server:
  port: 80


spring:
  application:
    name: bc-cms-web
  http:
    encoding: { charset: UTF-8, force: true, enabled: true }
  resources:
    chain:
      strategy:
        content:
          paths: /**
          enabled: true
  jackson:
    deserialization: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    enabled: true
    check-template: true
    content-type: text/html
    mode: LEGACYHTML5

info: bc-cms-web